### ISSUE TITLE
Sonar start timeout should be configurable

### ISSUE THREAD

**Issue by superbiche** [bitnami/bitnami-docker-sonarqube#13]
**Description**

The timeout of 300s makes Sonar Pod terminate in the middle of the init process, specifically in a Kubernetes multi-tenant cluster with geographically distant nodes.

Image tag: bitnami/sonarqube:7.9.1-r31

**Steps to reproduce the issue:**

1. Setup a multi-tenant Kubernetes cluster with NodeA in Paris, FR and NodeB in Helsinki,FIN (or simulate a slower network between A and B)
2. Deploy a PostgreSQL database pod in NodeB
3. Deploy manifest for Sonar (see below)
4. Run `kubectl exec -it deploy/sonarqube /bin/bash` to enter the container
5. Run `tail -f /opt/bitnami/sonarqube/logs/*.log` 

**Describe the results you received:**
The timeout of 300s stops the pod while the Web app log shows it's still starting

**Describe the results you expected:**

The init process should last longer to give enough time to Sonar to start

**Additional information you deem important (e.g. issue happens only occasionally):**

StatefulSet manifest
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  namespace: km-apps
spec:
  selector:
    matchLabels:
      app: sonarqube
  serviceName: sonar
  replicas: 1
  template:
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - image: bitnami/sonarqube:7.9.1-r31
          name: sonarqube
          env:
            - name: POSTGRESQL_HOST
              value: km-apps-sonarqube-db
            - name: SONARQUBE_DATABASE_NAME
              value: sonar
            - name: SONARQUBE_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sonar.km-apps-sonarqube-db.credentials
                  key: username
            - name: SONARQUBE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonar.km-apps-sonarqube-db.credentials
                  key: password
            - name: SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS
              value: "-Dnode.store.allow_mmapfs=false"
            - name: "sonar.core.serverBaseURL"
              value: https://sonarqube.example.com
          ports:
            - containerPort: 9000
              name: sonarqube
          volumeMounts:
          - name: sonarqube-data
            mountPath: /bitnami
  volumeClaimTemplates:
    - metadata:
        name: sonarqube-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-ssd
        resources:
          requests:
            storage: 10Gi
```

Last relevant lines of logs
```
==> /opt/bitnami/sonarqube/logs/es.log <==
2019.08.11 17:41:23 INFO  es[][o.e.c.m.MetaDataCreateIndexService] [users] creating index, cause [api], templates [], shards [1]/[0], mappings []
2019.08.11 17:41:23 INFO  es[][o.e.c.r.a.AllocationService] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[users][0]] ...]).
2019.08.11 17:41:23 INFO  es[][o.e.c.m.MetaDataMappingService] [users/QZFq3TUdQOySgN9NXuWTmg] create_mapping [user]
2019.08.11 17:41:23 INFO  es[][o.e.c.m.MetaDataCreateIndexService] [views] creating index, cause [api], templates [], shards [5]/[0], mappings []
2019.08.11 17:41:24 INFO  es[][o.e.c.r.a.AllocationService] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[views][4]] ...]).
2019.08.11 17:41:24 INFO  es[][o.e.c.m.MetaDataMappingService] [views/u54B1xhvTbmlaQ_O7kkE2Q] create_mapping [view]

==> /opt/bitnami/sonarqube/logs/web.log <==
2019.08.11 17:41:23 INFO  web[][o.s.s.e.IndexCreator] Create type users/user
2019.08.11 17:41:23 INFO  web[][o.s.s.e.IndexCreator] Create index [views]
2019.08.11 17:41:24 INFO  web[][o.s.s.e.IndexCreator] Create type views/view
2019.08.11 17:41:24 INFO  web[][o.s.s.s.LogServerId] Server ID: 5E67B154-AWyBq3BOTQnKYkUA3NIU
2019.08.11 17:41:24 WARN  web[][o.s.s.a.LogOAuthWarning] For security reasons, OAuth authentication should use HTTPS. You should set the property 'Administration > Configuration > Server base URL' to a HTTPS URL.
2019.08.11 17:41:25 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/plugins/download
2019.08.11 17:41:25 WARN  web[][o.s.a.s.w.WebService$Action] The response example is not set on action api/permissions/search_templates
2019.08.11 17:41:25 INFO  web[][o.s.s.t.TelemetryDaemon] Sharing of SonarQube statistics is enabled.
2019.08.11 17:41:25 INFO  web[][o.s.s.n.NotificationDaemon] Notification service started (delay 60 sec.)
2019.08.11 17:41:25 INFO  web[][o.s.s.s.GeneratePluginIndex] Generate scanner plugin index
2019.08.11 17:41:25 INFO  web[][o.s.s.s.RegisterPlugins] Register plugins
2019.08.11 17:41:26 INFO  web[][o.s.s.s.RegisterMetrics] Register metrics
2019.08.11 17:41:30 INFO  web[][o.s.s.r.RegisterRules] Register rules
2019.08.11 17:45:08 INFO  web[][o.s.s.q.BuiltInQProfileRepositoryImpl] Load quality profiles
2019.08.11 17:45:09 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register quality profiles
2019.08.11 17:45:09 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile css/Sonar way
2019.08.11 17:45:10 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile scala/Sonar way
2019.08.11 17:45:10 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile jsp/Sonar way
2019.08.11 17:45:10 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile go/Sonar way
2019.08.11 17:45:10 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile kotlin/Sonar way
2019.08.11 17:45:10 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile js/Sonar way Recommended
2019.08.11 17:45:11 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile js/Sonar way
2019.08.11 17:45:11 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile py/Sonar way
2019.08.11 17:45:11 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile ruby/Sonar way
2019.08.11 17:45:12 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile cs/Sonar way
2019.08.11 17:45:32 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile java/Sonar way
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:26:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 63
 Running: 43
 Paused: 0
 Stopped: 20
Images: 49
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 5.2.1-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.7GiB
Name: example.com
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

I'm going to use podAffinity to force the DB and Sonarqube to run on the same node, but for a first install we shouldn't be forced to optimize resource location.

---
EDIT: used nodeAffinity to force the colocation of Sonar with the DB master, Sonar started in less than 60 seconds.
