### ISSUE TITLE
can't run with docker-compose on Ubuntu 18.04 (log entry not found)

### ISSUE THREAD

**Issue by chovy** [bitnami/bitnami-docker-sonarqube#15]
```
version: '2'
  
services:
  postgresql:
    image: 'bitnami/postgresql:10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  sonarqube:
    image: bitnami/sonarqube:7
    ports:
      - '9210:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
```

when I run `docker-compose up --build` it just hangs on starting app.....then times out with an error.
```
sonarqube_1   | sonarqu INFO  ==> Starting app...
sonarqube_1   | sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.
sonarqube_1   | Error executing 'postInstallation': Log entry not found after 300 s.```



$ docker-compose -v
docker-compose version 1.17.1, build unknown
