### ISSUE TITLE
JDBC connection failure when using non-standard postgresql port

### ISSUE THREAD

**Issue by oetlinge** [bitnami/bitnami-docker-sonarqube#19]
**Description**

Setting up bitnami dockerized SonarQube instance with docker compose and trying to target a remote Postgresql database listening on a port other than the default (5432).  I've confirmed the database credentials specified in the docker-compose.yml file are correct, but the web.log file in the SonarQube container suggests the POSTGRESQL_PORT_NUMBER variable is being ignored.

**Steps to reproduce the issue:**

1. Created docker-compose.yml file with definition for SonarQube as below:
```
    sonarqube:
        image: 'bitnami/sonarqube:8'
        ports:
          - '9000:9000'
        environment:
          - POSTGRESQL_HOST=3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud
          - POSTGRESQL_PORT_NUMBER=30408
          - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
          - SONARQUBE_DATABASE_USER=<db_user>
          - SONARQUBE_DATABASE_PASSWORD=<db_password>
          - SONARQUBE_USERNAME=admin
          - SONARQUBE_PASSWORD=bitnami
          - SONARQUBE_START_TIMEOUT=600
          - NAMI_LOG_LEVEL=trace
        volumes:
          - sonarqube_data:/bitnami
```
2. Start container via docker-compose
3. Examine contents of docker container.

**Describe the results you received:**

Although sonarqube-inputs.json contains input mapping for database server port:
 `"databaseServerPort": "{{$global.env.POSTGRESQL_PORT_NUMBER}}"`

opt/bitnami/sonarqube/conf/sonar.properties specifies sonar.jdbc.url as:
`sonar.jdbc.url=jdbc:postgresql://3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf
10402584b5f01db462d330.databases.appdomain.cloud/bitnami_sonarqube` and there is no mention of the port number.

opt/bitnami/sonarqube/logs/web.log confirms the problem with jdbc url:
```
2020.03.19 14:07:21 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud/bitnami_sonarqube
2020.03.19 14:07:31 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Fail to connect to database
```

**Describe the results you expected:**

Specified port from POSTGRESQL_PORT_NUMBER should be applied to jdbc connection url.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-693.21.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.639GiB
 Name: sectestcoc
 ID: OZ3W:ISPV:SMSX:4Z7O:M3OM:HPBC:P5AC:E2CA:6GNW:33Z5:4WTM:O77M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  bxv8v141.cn.ibm.com
  wcnexus.torolab.ibm.com
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
