### ISSUE TITLE
Error executing 'postInstallation': Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by senzacionale** [bitnami/bitnami-docker-sonarqube#3]
```

Welcome to the Bitnami sonarqube container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues


nami    INFO  Initializing postgresql-client
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing sonarqube
sonarqu INFO  ==> Creating server folders...
sonarqu INFO  ==> Configuring database parameters...
sonarqu INFO  ==> Configuring server parameters...
sonarqu INFO  ==> Configure permissions...
sonarqu INFO  ==> Initializing SonarQube from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre INFO  PostgreSQL server listening and working at postgresql:5432
sonarqu INFO  ==> Starting app...
sonarqu INFO  ==> Configuring username...
sonarqu INFO  ==> Configuring salt and password...
sonarqu INFO  ==> Enabling authentication...
Error executing 'postInstallation': Cannot read property 'trim' of undefined
```
any ideas why?

**Comment by andresbono** [comment]
Hi @senzacionale, how are you running the container? If you could share with us the specific `docker-compose.yml` file or `docker run` command that you are using, that would be great.

**Comment by andresbono** [comment]
Hi @senzacionale, we can't reproduce the issue. Could you copy & paste the command or specific `docker-compose.yml` file that you are using? That way we may be able to reproduce it.

**Comment by nazim-basha-vwcredit** [comment]
I am getting the same error too.

**Comment by marcosbc** [comment]
Hi @nazim-basha-vwcredit, we're still unable to reproduce this issue. We are using this `docker-compose.yml`:

```
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:10'
    environment:
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
      - POSTGRESQL_PASSWORD=bitnami1234
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami'
  sonarqube:
    image: bitnami/sonarqube:latest
    ports:
      - '80:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
```

Then we run `docker-compose up -d`, `docker logs -f` and see everything initialize properly.

Is there anything we're missing?
