### ISSUE TITLE
Cannot bind mount logs and data and plugin folders to host

### ISSUE THREAD

**Issue by PhungXuanAnh** [bitnami/bitnami-docker-sonarqube#37]
I want to mount `opt/bitnami/sonarqube/logs` and `opt/bitnami/sonarqube/data` and `opt/bitnami/sonarqube/extensions/plugins` folder and data folder inside container to host but these folder is already created, so I can't

**Comment by carrodher** [comment]
Those folders are already mounted in order to persist the application, see https://github.com/bitnami/bitnami-docker-sonarqube#persisting-your-application
What is your specific use case?

**Comment by PhungXuanAnh** [comment]
@carrodher , I try again and I can mount folder `data` and `extensions`, but I still cannot mount folder `logs`

**Comment by carrodher** [comment]
Can you share what are the changes you are implementing in the docker-compose to mount the volumes? What is the error you're receiving? Also it would be useful for us to understand what is your goal, what are the reasons why you can mount those specific dirs in that way?

**Comment by PhungXuanAnh** [comment]
@carrodher , I am using this

```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    ports:
      - '80:9000'
    volumes:
      - './sonarqube_data:/bitnami/sonarqube'
      - './sonarqube_log:/opt/bitnami/sonarqube/logs'
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
volumes:
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
```

I encountered permission error when mount log folder, but sudo chmod 777 helped

**Comment by carrodher** [comment]
Yes, you should set the proper permission to the local folder (the one you are going to mount into the container).

I used the following docker-compose (where the `sonarqube_data` volume was removed since it is going to be mounted from the host):
```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    ports:
      - '80:9000'
    volumes:
      - '/tmp/sonarqube_data:/bitnami/sonarqube'
      - '/tmp/sonarqube_log:/opt/bitnami/sonarqube/logs'
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
volumes:
  postgresql_data:
    driver: local
```
And those are the steps I followed:
```console
$ mkdir -m 777 /tmp/sonarqube_data /tmp/sonarqube_log
$ docker-compose up
postgresql_1  | postgresql 11:36:30.98
sonarqube_1   | sonarqube 11:36:32.39
postgresql_1  | postgresql 11:36:30.98 Welcome to the Bitnami postgresql container
postgresql_1  | postgresql 11:36:30.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
sonarqube_1   | sonarqube 11:36:32.39 Welcome to the Bitnami sonarqube container
sonarqube_1   | sonarqube 11:36:32.39 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube_1   | sonarqube 11:36:32.39 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
postgresql_1  | postgresql 11:36:30.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
sonarqube_1   | sonarqube 11:36:32.40
postgresql_1  | postgresql 11:36:30.99
postgresql_1  | postgresql 11:36:31.00 INFO  ==> ** Starting PostgreSQL setup **
postgresql_1  | postgresql 11:36:31.02 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql_1  | postgresql 11:36:31.02 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql_1  | postgresql 11:36:31.03 INFO  ==> Loading custom pre-init scripts...
postgresql_1  | postgresql 11:36:31.03 INFO  ==> Initializing PostgreSQL database...
postgresql_1  | postgresql 11:36:31.05 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql_1  | postgresql 11:36:31.05 INFO  ==> Generating local authentication configuration
postgresql_1  | postgresql 11:36:32.24 INFO  ==> Starting PostgreSQL in background...
sonarqube_1   | sonarqube 11:36:32.40 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube_1   | sonarqube 11:36:32.45 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
sonarqube_1   | sonarqube 11:36:32.45 INFO  ==> Creating SonarQube configuration
postgresql_1  | postgresql 11:36:32.47 INFO  ==> Creating user bn_sonarqube
postgresql_1  | postgresql 11:36:32.49 INFO  ==> Granting access to "bn_sonarqube" to the database "bitnami_sonarqube"
sonarqube_1   | sonarqube 11:36:32.50 INFO  ==> Trying to connect to the database server
postgresql_1  | postgresql 11:36:32.52 INFO  ==> Setting ownership for the 'public' schema database "bitnami_sonarqube" to "bn_sonarqube"
postgresql_1  | postgresql 11:36:32.55 INFO  ==> Configuring replication parameters
postgresql_1  | postgresql 11:36:32.58 INFO  ==> Configuring fsync
postgresql_1  | postgresql 11:36:32.60 INFO  ==> Loading custom scripts...
postgresql_1  | postgresql 11:36:32.61 INFO  ==> Enabling remote connections
postgresql_1  | postgresql 11:36:32.62 INFO  ==> Stopping PostgreSQL...
postgresql_1  | waiting for server to shut down.... done
postgresql_1  | server stopped
postgresql_1  | postgresql 11:36:32.73 INFO  ==> ** PostgreSQL setup finished! **
postgresql_1  |
postgresql_1  | postgresql 11:36:32.76 INFO  ==> ** Starting PostgreSQL **
postgresql_1  | 2021-07-30 11:36:32.787 GMT [1] LOG:  pgaudit extension initialized
postgresql_1  | 2021-07-30 11:36:32.793 GMT [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgresql_1  | 2021-07-30 11:36:32.794 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql_1  | 2021-07-30 11:36:32.794 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgresql_1  | 2021-07-30 11:36:32.799 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql_1  | 2021-07-30 11:36:32.806 GMT [145] LOG:  database system was shut down at 2021-07-30 11:36:32 GMT
postgresql_1  | 2021-07-30 11:36:32.814 GMT [1] LOG:  database system is ready to accept connections
sonarqube_1   | sonarqube 11:36:37.54 INFO  ==> Ensuring SonarQube directories exist
sonarqube_1   | sonarqube 11:36:37.56 INFO  ==> Starting SonarQube in background
sonarqube_1   | sonarqube 11:36:38.10 INFO  ==> Waiting for SonarQube to start...
sonarqube_1   | sonarqube 11:37:20.25 INFO  ==> Configuring user credentials
sonarqube_1   | sonarqube 11:37:20.27 INFO  ==> Stopping SonarQube
sonarqube_1   | sonarqube 11:37:23.35 INFO  ==> Persisting SonarQube installation
sonarqube_1   | sonarqube 11:37:23.60 INFO  ==> ** SonarQube setup finished! **
sonarqube_1   |
sonarqube_1   | sonarqube 11:37:23.63 INFO  ==> ** Starting SonarQube **
sonarqube_1   | Running SonarQube...
```

If you find some issues, you can also add the `BITNAMI_DEBUG=true` environment variable to help you see what can be the issue.
