### ISSUE TITLE
ERROR Pattern SonarQube is up was not found in SonarQube log

### ISSUE THREAD

**Issue by SOIT-SF** [bitnami/bitnami-docker-sonarqube#4]
Installation of SonarQubes fails after running docker-compose up here is what we see.

sonarqube_1   | sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.

1. Create docker-compose file
2. Add volumes to correct locations
3. Run user root for postgres (needed to do this on postgres because of another issue)
4. Ran with user root and no user for container sonarqube

Example of configuration

version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    user: root
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=user_name
      - POSTGRESQL_DATABASE=database_name
      - POSTGRESQL_PASSWORD=XXXXXXXXXXXXXXXX
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /docker/Sonarqubes/data/postgresql_data:/bitnami
  sonarqube:
    image: bitnami/sonarqube:latest
    user: root
    ports:
      - 9000:9000
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_NAME=database_name
      - SONARQUBE_DATABASE_USER=user_name
      - SONARQUBE_DATABASE_PASSWORD=XXXXXXXXXXXXXX
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /docker/Sonarqubes/data/sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local

Here is what happens when starting 

Attaching to sonarqubes_sonarqube_1, sonarqubes_postgresql_1
sonarqube_1   |
sonarqube_1   | Welcome to the Bitnami sonarqube container
sonarqube_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube_1   |
postgresql_1  |
postgresql_1  | Welcome to the Bitnami postgresql container
postgresql_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql_1  |
sonarqube_1   | nami    INFO  Initializing postgresql-client
sonarqube_1   | nami    INFO  postgresql-client successfully initialized
postgresql_1  | nami    INFO  Initializing postgresql
postgresql_1  | postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgresql_1  | postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgresql_1  | postgre INFO  ==> Deploying PostgreSQL with persisted data...
postgresql_1  | postgre INFO  ==> Cleaning stale postmaster.pid file...
postgresql_1  | postgre INFO  ==> Configuring PostgreSQL...
postgresql_1  | postgre INFO  ==> Configuring replication parameters...
postgresql_1  | postgre INFO  ==> Configuring permissions for config files...
postgresql_1  | postgre INFO
postgresql_1  | postgre INFO  ########################################################################
postgresql_1  | postgre INFO   Installation parameters for postgresql:
postgresql_1  | postgre INFO     Persisted data and properties have been restored.
postgresql_1  | postgre INFO     Any input specified will not take effect.
postgresql_1  | postgre INFO   This installation requires no credentials.
postgresql_1  | postgre INFO  ########################################################################
postgresql_1  | postgre INFO
postgresql_1  | nami    INFO  postgresql successfully initialized
postgresql_1  | INFO  ==> Starting postgresql...
sonarqube_1   | nami    INFO  Initializing sonarqube
sonarqube_1   | sonarqu INFO  ==> Creating server folders...
sonarqube_1   | sonarqu INFO  ==> Configuring database parameters...
sonarqube_1   | sonarqu INFO  ==> Configuring server parameters...
sonarqube_1   | sonarqu INFO  ==> Configure permissions...
postgresql_1  | 2019-01-11 19:29:44.910 GMT [63] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql_1  | 2019-01-11 19:29:44.910 GMT [63] LOG:  listening on IPv6 address "::", port 5432
postgresql_1  | 2019-01-11 19:29:44.914 GMT [63] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql_1  | 2019-01-11 19:29:44.928 GMT [64] LOG:  database system was interrupted; last known up at 2019-01-11 19:27:10 GMT
postgresql_1  | 2019-01-11 19:29:44.948 GMT [64] LOG:  database system was not properly shut down; automatic recovery in progress
postgresql_1  | 2019-01-11 19:29:44.952 GMT [64] LOG:  redo starts at 0/15C1820
postgresql_1  | 2019-01-11 19:29:44.952 GMT [64] LOG:  invalid record length at 0/15C1858: wanted 24, got 0
postgresql_1  | 2019-01-11 19:29:44.952 GMT [64] LOG:  redo done at 0/15C1820
postgresql_1  | 2019-01-11 19:29:44.963 GMT [63] LOG:  database system is ready to accept connections
sonarqube_1   | sonarqu INFO  ==> Initializing SonarQube from scratch...
sonarqube_1   | postgre INFO  Trying to connect to PostgreSQL server
sonarqube_1   | postgre INFO  Found PostgreSQL server listening at postgresql:5432
sonarqube_1   | postgre INFO  PostgreSQL server listening and working at postgresql:5432
sonarqube_1   | sonarqu INFO  ==> Starting app...
sonarqube_1   | sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.
sonarqube_1   | Error executing 'postInstallation': Log entry not found after 300 s.

**Comment by javsalgar** [comment]
Hi,

I see that the environment variables differ a bit from the ones that we have in our docker-compose

```
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:10'
    volumes:
      - 'postgresql_data:/bitnami'
  sonarqube:
    image: bitnami/sonarqube:7-debian-9
    ports:
      - '80:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
```
Could you change them so they match this better?

**Comment by shunn45** [comment]
Hello, the configuration example below doesn't works too (I got "Connection with 'postgres' user is unsuccessful " error) .... I used docker configuration from GitHub:

$ docker run -d --name sonarqube -p 80:9000 \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e SONARQUBE_DATABASE_USER=bn_sonarqube \
  -e SONARQUBE_DATABASE_NAME=bitnami_sonarqube \
  -e SONARQUBE_DATABASE_PASSWORD=xxxxxx \
  --net sonarqube-tier \
  --volume /path/to/sonarqube-persistence:/bitnami \
  bitnami/sonarqube:latest

Could you help please?

**Comment by javsalgar** [comment]
Hi,

You may need to add the information for creating the postgres database as well, check the docker-compose file above and try to add these env vars. Please let us know if it works.

**Comment by shunn45** [comment]
Hi, Thanks for the answer!

Following steps was proceeded:
$ docker network create sonarqube-tier

$ docker volume create --name postgresql_data

$ docker run -d --name postgresql \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e POSTGRESQL_USERNAME=bn_sonarqube \
  -e POSTGRESQL_DATABASE=bitnami_sonarqube \
  -e POSTGRESQL_PASSWORD=bitnami1234 \
  --net sonarqube-tier \
  --volume postgresql_data:/bitnami \
  bitnami/postgresql:latest

$ docker volume create --name sonarqube_data

$ docker run -d --name sonarqube -p 80:9000 \
  -e ALLOW_EMPTY_PASSWORD=yes \
  -e SONARQUBE_DATABASE_USER=bn_sonarqube \
  -e SONARQUBE_DATABASE_NAME=bitnami_sonarqube \
  -e SONARQUBE_DATABASE_PASSWORD=bitnami1234 \
  --net sonarqube-tier \
  --volume sonarqube_data:/bitnami \
  bitnami/sonarqube:latest

Env: AWS EC2 t2.micro

Thanks,
Haim

**Comment by Jamesking56** [comment]
I am getting this same issue with the default untouched `docker-compose.yml` in the master branch

**Comment by shunn45** [comment]
Hi, Solved this issue.. problem in java memory thresholds - We cannot start sonarqube on EC2 t2.micro, since no enough memory provided for java start command. 
t2.medium works (very very slow... takes ~ 10 min for 4 java source files, but works ... not recommend for production)... so need t2. large at least ... 
Regards,
Haim

**Comment by javsalgar** [comment]
Hi,

Good to know that you solved the issue! @Jamesking56 could you confirm if using bigger instances solves the issue for you as well?

**Comment by Jamesking56** [comment]
Using a different docker container solved my issue, even with the small instance:

```yaml
version: "2"

services:
  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "80:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
```
