### ISSUE TITLE
Unterminated sed on Azure instance

### ISSUE THREAD

**Issue by aistiszen** [bitnami/bitnami-docker-sonarqube#46]
### Name and Version

bitnami/sonarqube:9

### What steps will reproduce the bug?

Was trying to run bitnami/sonarqube:9 in Azure Kubernetes setup and kept getting:
```
sed: -e expression #1, char 73: unterminated `s' command
```
Cloned repo, uncommented debug lines in bash files and got this:

```
+ grep -q -E '^\s*(#\s*)?sonar\.jdbc\.username\s*=.*' /opt/bitnami/sonarqube/conf/sonar.properties
+ replace_in_file /opt/bitnami/sonarqube/conf/sonar.properties '^\s*(#\s*)?sonar\.jdbc\.username\s*=.*' 'sonar.jdbc.username=bn_sonarqube
'
+ local filename=/opt/bitnami/sonarqube/conf/sonar.properties
+ local 'match_regex=^\s*(#\s*)?sonar\.jdbc\.username\s*=.*'
+ local 'substitute_regex=sonar.jdbc.username=bn_sonarqube
'
+ local posix_regex=true
+ local result
+ local -r $'del=\001'
+ [[ true = true ]]
++ sed -E 's^\s*(#\s*)?sonar\.jdbc\.username\s*=.*sonar.jdbc.username=bn_sonarqubeg' /opt/bitnami/sonarqube/conf/sonar.properties
sed: -e expression #1, char 73: unterminated `s' command
+ result=
```

I'm using env variables and Kubernetes secrets as in deployment.yaml as such:
```yaml
       env:
        - name: SONARQUBE_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_DATABASE_USER
              name: database-secrets
        - name: SONARQUBE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_DATABASE_PASSWORD
              name: database-secrets
```
The offending function is in libfile.sh, which already has a comment about mounting ConfigMaps, so it looks like there's a case for secret files too since the plain env variable seems to pass through this. 

### What do you see instead?
```
sed: -e expression #1, char 73: unterminated `s' command
```
